// Central configuration for the Fyredocs k6 load-test suite.
// Everything that varies between runs (target, scale, job mix, SLOs) lives here
// so the scenario files stay declarative. Override via env: `k6 run -e KEY=val`.

// ---------------------------------------------------------------------------
// Target
// ---------------------------------------------------------------------------
export const BASE_URL = (__ENV.BASE_URL || 'http://localhost:8080').replace(/\/$/, '');

// Plan the provisioned test users should be on. NOTE: the backend hardened
// PUT /auth/plan to admin/super-admin only, and it only changes the *caller's*
// own plan — a freshly signed-up load user (role "user") cannot self-upgrade.
// So the plan is set at the DB level by seed-pro-users.sh, NOT by k6. This
// value is only used for the best-effort self-upgrade attempt (a no-op / 403
// for non-admin users). All current fixtures (<=38MB) fit the default `free`
// plan (50MB/10 files); `pro` (500MB/50 files) is headroom.
export const TEST_PLAN = __ENV.TEST_PLAN || 'pro';

// How many users setup() provisions and VUs round-robin across. In capacity
// mode signup/login limits are raised, so a pool is cheap and avoids per-IP /
// per-user rate skew. Reuse fixed creds instead by setting USER_EMAIL/USER_PASSWORD.
export const USER_POOL_SIZE = Number(__ENV.USER_POOL_SIZE || 10);
export const FIXED_EMAIL = __ENV.USER_EMAIL || '';
export const FIXED_PASSWORD = __ENV.USER_PASSWORD || '';
export const PASSWORD = __ENV.PASSWORD || 'LoadTest!23456';

// Pre-seeded user pool (opt-in). When set, setup() logs in these existing users
// instead of signing up fresh ones, and skips the plan self-upgrade — use this
// with seed-pro-users.sh to run the whole suite as `pro` users. Provide either a
// comma list of emails (USER_EMAILS) or a prefix (USER_EMAIL_PREFIX) that maps to
// `${prefix}+1..USER_POOL_SIZE@${SEED_EMAIL_DOMAIN}`. Empty -> dynamic signup.
export const SEED_EMAIL_DOMAIN = __ENV.SEED_EMAIL_DOMAIN || 'loadtest.fyredocs.local';
export const SEEDED_EMAILS = (function seededEmails() {
  const list = (__ENV.USER_EMAILS || '').split(',').map((s) => s.trim()).filter(Boolean);
  if (list.length) return list;
  const prefix = (__ENV.USER_EMAIL_PREFIX || '').trim();
  if (!prefix) return [];
  const out = [];
  for (let i = 1; i <= Math.max(1, USER_POOL_SIZE); i++) out.push(`${prefix}+${i}@${SEED_EMAIL_DOMAIN}`);
  return out;
})();

// Upload mode for job scenarios: 'presigned' (init -> PUT parts -> complete, the
// SPA's path — DEFAULT) or 'multipart' (single direct request). NOTE: multipart
// job-create goes through the gateway's ~1MB body cap (only /api/upload/* is
// exempt), so it only works for tiny files; use it just for small-file tests.
export const UPLOAD_MODE = __ENV.UPLOAD_MODE || 'presigned';

// Completion strategy: 'poll' (GET status w/ backoff) or 'sse' (/api/jobs/:id/events).
export const COMPLETION = __ENV.COMPLETION || 'poll';
export const POLL_INTERVAL_MS = Number(__ENV.POLL_INTERVAL_MS || 1500);
export const JOB_TIMEOUT_MS = Number(__ENV.JOB_TIMEOUT_MS || 120000);
// Fraction of completed jobs whose result we also download (exercises the
// gateway object-proxy / presigned path). 0..1.
export const DOWNLOAD_RATIO = Number(__ENV.DOWNLOAD_RATIO || 0.3);

// ---------------------------------------------------------------------------
// File-size distribution (weighted pick of a size class per job)
// ---------------------------------------------------------------------------
// Classes map to fixture files generated by fixtures/generate.sh.
export const SIZE_CLASSES = [
  { name: 'small', weight: 70 },   // ~0.5-3 MB  — the bulk of real traffic
  { name: 'medium', weight: 25 },  // ~5-20 MB
  { name: 'large', weight: 5 },    // ~50 MB     — stresses tmpfs + bandwidth
];

// ---------------------------------------------------------------------------
// Tool matrix — the realistic job mix.
// group: gateway path segment; fixture: which fixture category to feed;
// options: server-confirmed option fields; multi: send N files (merge);
// weight: relative share in the mixed-realistic scenario.
// Tool names + options verified against job-service/internal/routing/routing.go
// and each service's processing.go switch.
// ---------------------------------------------------------------------------
export const TOOL_MATRIX = [
  // optimize-pdf (heavy: Ghostscript / Tesseract)
  { tool: 'compress-pdf', group: 'optimize-pdf', fixture: 'pdf', options: { quality: 'medium' }, weight: 25 },
  { tool: 'ocr-pdf',      group: 'optimize-pdf', fixture: 'scanned-pdf', options: { language: 'eng', dpi: 150 }, weight: 5 },
  { tool: 'repair-pdf',   group: 'optimize-pdf', fixture: 'pdf', options: {}, weight: 3 },

  // organize-pdf (fast: pdfcpu)
  { tool: 'merge-pdf',    group: 'organize-pdf', fixture: 'pdf', options: {}, multi: 2, weight: 15 },
  { tool: 'split-pdf',    group: 'organize-pdf', fixture: 'pdf', options: { mode: 'range', range: '1-3,5' }, weight: 10 },
  { tool: 'rotate-pdf',   group: 'organize-pdf', fixture: 'pdf', options: { rotation: 90, applyToPages: 'all' }, weight: 4 },
  { tool: 'remove-pages', group: 'organize-pdf', fixture: 'pdf', options: { pages: '2,4' }, weight: 3 },
  { tool: 'watermark-pdf',group: 'organize-pdf', fixture: 'pdf', options: { type: 'text', text: 'DRAFT', position: 'diagonal', opacity: 30, fontSize: 48 }, weight: 4 },
  { tool: 'add-page-numbers', group: 'organize-pdf', fixture: 'pdf', options: { position: 'bc', format: '{n} of {total}' }, weight: 2 },

  // convert-to-pdf (heavy: LibreOffice via unoserver)
  { tool: 'word-to-pdf',  group: 'convert-to-pdf', fixture: 'docx', options: {}, weight: 15 },
  { tool: 'excel-to-pdf', group: 'convert-to-pdf', fixture: 'xlsx', options: {}, weight: 4 },
  { tool: 'ppt-to-pdf',   group: 'convert-to-pdf', fixture: 'pptx', options: {}, weight: 3 },
  { tool: 'image-to-pdf', group: 'convert-to-pdf', fixture: 'image', options: {}, multi: 2, weight: 6 },

  // convert-from-pdf (pdf2docx / LibreOffice / poppler)
  { tool: 'pdf-to-word',  group: 'convert-from-pdf', fixture: 'pdf', options: {}, weight: 10 },
  { tool: 'pdf-to-text',  group: 'convert-from-pdf', fixture: 'pdf', options: {}, weight: 5 },
  { tool: 'pdf-to-image', group: 'convert-from-pdf', fixture: 'pdf', options: { outputExt: '.jpg' }, weight: 3 },
];

// Per-group view (for the per-tool scenarios).
export function toolsForGroup(group) {
  return TOOL_MATRIX.filter((t) => t.group === group);
}

// ---------------------------------------------------------------------------
// Load profiles — arrival rates tuned per target. Pick with -e PROFILE=vps40.
// rates are PER MINUTE (jobs/min for tool scenarios, req/min for browse).
// ---------------------------------------------------------------------------
const PROFILES = {
  vps40: {
    job_rate: Number(__ENV.JOB_RATE || 90),     // start near the ~50-120/min estimate
    browse_rate: Number(__ENV.BROWSE_RATE || 1200),
    duration: __ENV.DURATION || '5m',
    preAllocVUs: 50,
    maxVUs: 300,
  },
  laptop: {
    job_rate: Number(__ENV.JOB_RATE || 12),
    browse_rate: Number(__ENV.BROWSE_RATE || 120),
    duration: __ENV.DURATION || '2m',
    preAllocVUs: 10,
    maxVUs: 60,
  },
};
export const PROFILE = PROFILES[__ENV.PROFILE || 'vps40'] || PROFILES.vps40;

// ---------------------------------------------------------------------------
// Thresholds / SLOs — a breach fails the run (good for CI / baselines).
// ---------------------------------------------------------------------------
export const THRESHOLDS = {
  http_req_failed: ['rate<0.02'],
  // gateway/API latency (excludes the long async job processing)
  'http_req_duration{kind:api}': ['p(95)<800', 'p(99)<2000'],
  // end-to-end job time (create -> completed) — generous; tune per baseline
  job_e2e: ['p(95)<60000'],
  job_success: ['rate>0.98'],
};
