version: '3.8'

services:
  convert-to-pdf:
    build:
      context: ./convert-to-pdf
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8083:8083"
    environment:
      PORT: "8083"
      DATABASE_URL: postgresql://user:password@db:5432/esydocs?sslmode=disable
    env_file:
      - ./convert-to-pdf/.env
    volumes:
      - uploads_data:/root/uploads
      - outputs_data:/root/outputs
    networks:
      - esydocs_net

networks:
  esydocs_net:
    external: true

volumes:
  uploads_data:
  outputs_data:
