services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      UPLOAD_SERVICE_URL: http://upload-service:8081
      CONVERT_FROM_PDF_URL: http://convert-from-pdf:8082
      CONVERT_TO_PDF_URL: http://convert-to-pdf:8083
    networks:
      - esydocs_net

networks:
  esydocs_net:
    external: true
