services:
  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      UPLOAD_SERVICE_URL: http://upload-service:8081
      REDIS_ADDR: redis:6379
    env_file:
      - ../.env
    networks:
      - fyredocs_net

networks:
  fyredocs_net:
    external: true
